### ISSUE TITLE
Can you provide a test login username and password?

### ISSUE THREAD

**Issue by ricefish888** [DFilyushin/lighthouse#13]
Can you provide a test login username and password?

Thank you!

**Comment by DFilyushin** [comment]
On first run in docker password created in terminal.
backend/api/docker-entrypoint.sh
echo "Create super user"
python manage.py createadmin
or
fixtures create many users with one password "password"

**Comment by 09Iota** [comment]
можно узнать о файле docker-test.sh ? в файле docker-compose-test.yml строчка 42 указывает на путь к файлу, которой не существует.
